/* DO NOT EDIT THIS FILE - it is machine generated */

# if (_IS_USED_WIN32_UTF8_WAPI)
#include "jni.h"
# else
#include <jni.h>
#endif
/* Header for class utils_BsDiff */

#ifndef _Included_utils_BsDiff
#define _Included_utils_BsDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_BsDiff
 * Method:    bsDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_utils_BsDiff_bsDiff(JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
